name: mit-phototoxicity
channels:
  - conda-forge
  - nodefaults
dependencies:
  - czifile==2019.7.2
  - dask
  - imageio==2.13.3
  - matplotlib==3.5.1
  - numpy==1.21.2
  - numba==0.55.1
  - pandas==1.3.5
  - scikit-image==0.19.1
  - scipy==1.7.3
  - seaborn==0.12.1
  - tifffile==2021.10.12
  - toolz==0.11.2
  - python=3.9.7
  - pyyaml==6.0
  - pillow==8.4.0
  - scikit-learn==1.2.1
  - pip:
    - opencv-python==4.5.3.56
    - opencv
    - nd2==0.1.6
    - slideio
    - nd2==0.1.6
