name: photofitt
channels:
  - conda-forge
  - nodefaults
dependencies:
  - numpy==1.24
  - python==3.10
  - jupyter==1.0.0
  - conda-build==24.5.1
  - pip==24.0
  - pip:
    - opencv-python==4.7.0.72
