name: photofitt
channels:
  - conda-forge
  - nodefaults
dependencies:
  - numpy==1.21.2
  - python=3.9.7
  - jupyter
  - conda-build
  - pip:
    - opencv-python>=4.5.3.56
    - nd2==0.1.6
    - connected-components-3d